spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    
  application:
    name: smart-suggestion-spring-ai

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8080 # porta do server admin, pode ser 8080 mesmo ou outra se você separar

spring.boot.admin:
  client:
    url: http://localhost:8080 # se for client e server na mesma app

logging:
  level:
    root: INFO
